#!/usr/bin/env node
var fs = require("fs");
var parser = require("./src/lua_parser").parser;

if (process.argv.length != 4) {
  console.log("Usage: lua2js <input.lua> <output.js>");
  process.exit(1);
}

fs.writeFile(process.argv[3], parser.parse(fs.readFileSync(process.argv[2], 'utf8')), function (err) {
  if (err) {
    throw err;
  }
});
