#!/usr/bin/env node
var fs = require("fs");
var parser = require("./src/lua_parser").parser;

if (process.argv.length != 4) {
  console.log("Usage: lua2js <input.lua> <output.js>");
  process.exit(1);
}

var source = fs.readFileSync(process.argv[2], 'utf8');
var script = "var lua_script = (function() {\n" +
  "  " + parser.parse(source).split("\n").join("\n  ") +
  "  return _G;\n" +
  "})();\n"

fs.writeFile(process.argv[3], script, function (err) {
  if (err) {
    throw err;
  }
});
